version: '3.1'

services:
    db:
        image: mariadb:10.3
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r
        volumes: 
            - /docker/apidb:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8082:80
        environment:
            - PMA_ARBITRARY=1

    rxtnet-api:
        restart: always
        depends_on: 
            - db
        build: .
        ports:
            - 8083:80